name: Release
on:
  schedule:
    - cron: '5 5 * * *'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

# Build on the oldest supported images, so we have broader compatibility
# Build with gcc-10 to prevent triggering #14150 (default is still gcc-9 on 20.04)
jobs:
  windows:
    runs-on: windows-2022
    env:
      DEPS_BUILD_DIR: ${{ format('{0}/nvim-deps', github.workspace) }}
      DEPS_PREFIX: ${{ format('{0}/nvim-deps/usr', github.workspace) }}
      CMAKE_BUILD_TYPE: "RelWithDebInfo"
    strategy:
      matrix:
        include:
          - config: MSVC_64
            archive: nvim-win64
    name: windows (${{ matrix.config }})
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build deps
        run: .\ci\build.ps1 -BuildDeps
      - name: build package
        run: .\ci\build.ps1 -Package
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.archive }}
          path: |
            build/${{ matrix.archive }}.msi
            build/${{ matrix.archive }}.zip
          retention-days: 1
